ctrl_interface=wpaspy_ctrl

network={
	# Don't change this field, the script relies on it
	id_str="attacker"

	# Network to test - attacker login
	ssid="testnetwork"
	psk="12345678"
}

network={
	# Don't change this field, the script relies on it
	id_str="victim"

	# Network to test - victim login
	ssid="testnetwork"
	psk="12345678"
}
